In [1]:
%load_ext autoreload
%autoreload 2

In [21]:
import os
from collections import defaultdict
import pandas as pd
from agreement_utils import extract_name, two_annotators_agreement, n_annotators_agreement
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Third Round Agreement - Inner Agreement Point-AI

In [22]:
conllu_annotated_files_path = "../../conllu_out_annotation/documents_59_to_63"

In [23]:
file_by_annotator = defaultdict(list)
conllu_annotated_files = os.listdir(conllu_annotated_files_path)
for f in conllu_annotated_files:
    file_by_annotator[extract_name(f)].append(f)
keep_singletons = False
calc_with_mentions = False


Arbel_vs_Ido = two_annotators_agreement("Arbel", "Ido", keep_singletons,calc_with_mentions, file_by_annotator, conllu_annotated_files_path, )
Arbel_vs_Elisheva = two_annotators_agreement("Arbel", "Elisheva", keep_singletons,calc_with_mentions, file_by_annotator, conllu_annotated_files_path,)
Elisheva_vs_Ido =  two_annotators_agreement("Elisheva", "Ido", keep_singletons,calc_with_mentions,file_by_annotator, conllu_annotated_files_path)

third_round_agreement = [
    ("Ido vs. Arbel No Singletons", Arbel_vs_Ido),
    ("Arbel vs. Elisheva  No Singletons", Arbel_vs_Elisheva),
    ("Elisheva vs. Ido No Singletons", Elisheva_vs_Ido)]

30 and 31 singletons are removed from the key and system files, respectively
mentions   Recall: 80.00  Precision: 85.71  F1: 82.76
muc        Recall: 62.50  Precision: 71.43  F1: 66.67
bcub       Recall: 72.22  Precision: 78.57  F1: 75.26
ceafe      Recall: 84.29  Precision: 84.29  F1: 84.29
lea        Recall: 66.67  Precision: 71.43  F1: 68.97
CoNLL score: 73.80
41 and 41 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 73.33  F1: 73.33
muc        Recall: 77.78  Precision: 70.00  F1: 73.68
bcub       Recall: 73.33  Precision: 68.33  F1: 70.75
ceafe      Recall: 64.29  Precision: 77.14  F1: 70.13
lea        Recall: 73.33  Precision: 66.67  F1: 69.84
CoNLL score: 71.10
47 and 59 singletons are removed from the key and system files, respectively
mentions   Recall: 68.89  Precision: 93.94  F1: 79.49
muc        Recall: 53.12  Precision: 80.95  F1: 64.15
bcub       Recall: 44.23  Precision: 83.03  F1: 57.71
ceafe      Recall: 54.54  Precision: 59.08  F1: 56.72
lea        Recall: 35.56  Precision: 75.76  F1: 48.40
CoNLL score: 56.75
29 and 24 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 83.87  F1: 91.23
muc        Recall: 100.00  Precision: 83.33  F1: 90.91
bcub       Recall: 100.00  Precision: 81.72  F1: 89.94
ceafe      Recall: 98.18  Precision: 83.08  F1: 90.00
lea        Recall: 100.00  Precision: 80.65  F1: 89.29
CoNLL score: 90.03
34 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 85.71  Precision: 88.24  F1: 86.96
muc        Recall: 79.17  Precision: 86.36  F1: 82.61
bcub       Recall: 77.62  Precision: 84.80  F1: 81.05
ceafe      Recall: 86.97  Precision: 79.72  F1: 83.19
lea        Recall: 73.33  Precision: 82.35  F1: 77.58
CoNLL score: 81.11
30 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 66.67  Precision: 100.00  F1: 80.00
muc        Recall: 62.50  Precision: 100.00  F1: 76.92
bcub       Recall: 62.22  Precision: 100.00  F1: 76.71
ceafe      Recall: 68.57  Precision: 96.00  F1: 80.00
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 77.16
41 and 45 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 100.00  F1: 84.62
muc        Recall: 66.67  Precision: 100.00  F1: 80.00
bcub       Recall: 64.44  Precision: 100.00  F1: 78.38
ceafe      Recall: 76.67  Precision: 92.00  F1: 83.64
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 79.25
47 and 70 singletons are removed from the key and system files, respectively
mentions   Recall: 44.44  Precision: 90.91  F1: 59.70
muc        Recall: 34.38  Precision: 84.62  F1: 48.89
bcub       Recall: 25.80  Precision: 86.36  F1: 39.73
ceafe      Recall: 37.69  Precision: 54.44  F1: 44.55
lea        Recall: 21.27  Precision: 81.82  F1: 33.76
CoNLL score: 41.73
29 and 26 singletons are removed from the key and system files, respectively
mentions   Recall: 92.31  Precision: 82.76  F1: 87.27
muc        Recall: 93.33  Precision: 82.35  F1: 87.50
bcub       Recall: 92.31  Precision: 80.46  F1: 85.98
ceafe      Recall: 89.09  Precision: 81.67  F1: 85.22
lea        Recall: 92.31  Precision: 79.31  F1: 85.32
CoNLL score: 86.00
34 and 37 singletons are removed from the key and system files, respectively
mentions   Recall: 88.57  Precision: 96.88  F1: 92.54
muc        Recall: 87.50  Precision: 95.45  F1: 91.30
bcub       Recall: 84.52  Precision: 94.79  F1: 89.36
ceafe      Recall: 85.97  Precision: 94.57  F1: 90.07
lea        Recall: 82.86  Precision: 93.75  F1: 87.97
CoNLL score: 89.68
26 and 24 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 93.55  F1: 96.67
muc        Recall: 100.00  Precision: 94.44  F1: 97.14
bcub       Recall: 100.00  Precision: 93.55  F1: 96.67
ceafe      Recall: 100.00  Precision: 92.31  F1: 96.00
lea        Recall: 100.00  Precision: 93.55  F1: 96.67
CoNLL score: 96.62
35 and 31 singletons are removed from the key and system files, respectively
mentions   Recall: 90.00  Precision: 64.29  F1: 75.00
muc        Recall: 80.00  Precision: 57.14  F1: 66.67
bcub       Recall: 85.00  Precision: 60.71  F1: 70.83
ceafe      Recall: 90.00  Precision: 64.29  F1: 75.00
lea        Recall: 80.00  Precision: 57.14  F1: 66.67
CoNLL score: 69.79
37 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 90.62  Precision: 85.29  F1: 87.88
muc        Recall: 86.36  Precision: 86.36  F1: 86.36
bcub       Recall: 84.90  Precision: 83.82  F1: 84.36
ceafe      Recall: 91.00  Precision: 75.83  F1: 82.73
lea        Recall: 81.25  Precision: 82.35  F1: 81.80
CoNLL score: 83.81
70 and 59 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 66.67  F1: 80.00
muc        Recall: 100.00  Precision: 61.90  F1: 76.47
bcub       Recall: 100.00  Precision: 53.94  F1: 70.08
ceafe      Recall: 82.54  Precision: 61.90  F1: 70.75
lea        Recall: 100.00  Precision: 51.73  F1: 68.19
CoNLL score: 71.37
45 and 41 singletons are removed from the key and system files, respectively
mentions   Recall: 81.82  Precision: 60.00  F1: 69.23
muc        Recall: 83.33  Precision: 50.00  F1: 62.50
bcub       Recall: 81.82  Precision: 48.89  F1: 61.21
ceafe      Recall: 69.33  Precision: 69.33  F1: 69.33
lea        Recall: 81.82  Precision: 44.44  F1: 57.60
CoNLL score: 62.66

In [24]:
Elisheva_vs_Ido

{'muc': {'recall': 0.8993939393939394,
  'precision': 0.6997113997113997,
  'f1': 0.7782874968169086},
 'bcub': {'recall': 0.9034280303030304,
  'precision': 0.6818289701022149,
  'f1': 0.7662811562659562},
 'ceafe': {'recall': 0.8657460317460318,
  'precision': 0.7273296703296703,
  'f1': 0.7876178107606678},
 'lea': {'recall': 0.8861363636363636,
  'precision': 0.6584404631842962,
  'f1': 0.7418387771348582}}

In [25]:
print(Arbel_vs_Ido)
Arbel_vs_Elisheva = two_annotators_agreement("Arbel", "Elisheva", keep_singletons,False, file_by_annotator, conllu_annotated_files_path,)
Elisheva_vs_Ido =  two_annotators_agreement("Elisheva", "Ido", keep_singletons,False,file_by_annotator, conllu_annotated_files_path)

third_round_agreement = [
    ("Ido vs. Arbel No Singletons", Arbel_vs_Ido),
    ("Arbel vs. Elisheva  No Singletons", Arbel_vs_Elisheva),
    ("Elisheva vs. Ido No Singletons", Elisheva_vs_Ido)]

{'muc': {'recall': 0.7451388888888888, 'precision': 0.7841558441558443, 'f1': 0.7560392143009474}, 'bcub': {'recall': 0.7348059964726631, 'precision': 0.7929188332224386, 'f1': 0.7494310842977099}, 'ceafe': {'recall': 0.7765211862044442, 'precision': 0.7666203404438698, 'f1': 0.7686462911342706}, 'lea': {'recall': 0.6977777777777778, 'precision': 0.753701832639214, 'f1': 0.708142439105378}}
30 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 66.67  Precision: 100.00  F1: 80.00
muc        Recall: 62.50  Precision: 100.00  F1: 76.92
bcub       Recall: 62.22  Precision: 100.00  F1: 76.71
ceafe      Recall: 68.57  Precision: 96.00  F1: 80.00
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 77.16
41 and 45 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 100.00  F1: 84.62
muc        Recall: 66.67  Precision: 100.00  F1: 80.00
bcub       Recall: 64.44  Precision: 100.00  F1: 78.38
ceafe      Recall: 76.67  Precision: 92.00  F1: 83.64
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 79.25
47 and 70 singletons are removed from the key and system files, respectively
mentions   Recall: 44.44  Precision: 90.91  F1: 59.70
muc        Recall: 34.38  Precision: 84.62  F1: 48.89
bcub       Recall: 25.80  Precision: 86.36  F1: 39.73
ceafe      Recall: 37.69  Precision: 54.44  F1: 44.55
lea        Recall: 21.27  Precision: 81.82  F1: 33.76
CoNLL score: 41.73
29 and 26 singletons are removed from the key and system files, respectively
mentions   Recall: 92.31  Precision: 82.76  F1: 87.27
muc        Recall: 93.33  Precision: 82.35  F1: 87.50
bcub       Recall: 92.31  Precision: 80.46  F1: 85.98
ceafe      Recall: 89.09  Precision: 81.67  F1: 85.22
lea        Recall: 92.31  Precision: 79.31  F1: 85.32
CoNLL score: 86.00
34 and 37 singletons are removed from the key and system files, respectively
mentions   Recall: 88.57  Precision: 96.88  F1: 92.54
muc        Recall: 87.50  Precision: 95.45  F1: 91.30
bcub       Recall: 84.52  Precision: 94.79  F1: 89.36
ceafe      Recall: 85.97  Precision: 94.57  F1: 90.07
lea        Recall: 82.86  Precision: 93.75  F1: 87.97
CoNLL score: 89.68
26 and 24 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 93.55  F1: 96.67
muc        Recall: 100.00  Precision: 94.44  F1: 97.14
bcub       Recall: 100.00  Precision: 93.55  F1: 96.67
ceafe      Recall: 100.00  Precision: 92.31  F1: 96.00
lea        Recall: 100.00  Precision: 93.55  F1: 96.67
CoNLL score: 96.62
35 and 31 singletons are removed from the key and system files, respectively
mentions   Recall: 90.00  Precision: 64.29  F1: 75.00
muc        Recall: 80.00  Precision: 57.14  F1: 66.67
bcub       Recall: 85.00  Precision: 60.71  F1: 70.83
ceafe      Recall: 90.00  Precision: 64.29  F1: 75.00
lea        Recall: 80.00  Precision: 57.14  F1: 66.67
CoNLL score: 69.79
37 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 90.62  Precision: 85.29  F1: 87.88
muc        Recall: 86.36  Precision: 86.36  F1: 86.36
bcub       Recall: 84.90  Precision: 83.82  F1: 84.36
ceafe      Recall: 91.00  Precision: 75.83  F1: 82.73
lea        Recall: 81.25  Precision: 82.35  F1: 81.80
CoNLL score: 83.81
70 and 59 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 66.67  F1: 80.00
muc        Recall: 100.00  Precision: 61.90  F1: 76.47
bcub       Recall: 100.00  Precision: 53.94  F1: 70.08
ceafe      Recall: 82.54  Precision: 61.90  F1: 70.75
lea        Recall: 100.00  Precision: 51.73  F1: 68.19
CoNLL score: 71.37
45 and 41 singletons are removed from the key and system files, respectively
mentions   Recall: 81.82  Precision: 60.00  F1: 69.23
muc        Recall: 83.33  Precision: 50.00  F1: 62.50
bcub       Recall: 81.82  Precision: 48.89  F1: 61.21
ceafe      Recall: 69.33  Precision: 69.33  F1: 69.33
lea        Recall: 81.82  Precision: 44.44  F1: 57.60
CoNLL score: 62.66

In [26]:
Arbel_vs_Elisheva

{'muc': {'recall': 0.68875,
  'precision': 0.9248457424928013,
  'f1': 0.7692326272761056},
 'bcub': {'recall': 0.658601275267942,
  'precision': 0.9232301462904913,
  'f1': 0.7403315832801202},
 'ceafe': {'recall': 0.715990675990676,
  'precision': 0.8373650793650793,
  'f1': 0.7669344733941006},
 'lea': {'recall': 0.6328693528693529,
  'precision': 0.9097570532915361,
  'f1': 0.7140941781106929}}

In [29]:
for name, score in third_round_agreement:
    print(name + " Conll score by muc, bcub, ceafe, lea  (without Mentions)")
    df = pd.DataFrame(score)
    df['mean'] = df.mean(axis=1)
    print(df['mean']['f1'])

Ido vs. Arbel No Singletons Conll score by muc, bcub, ceafe, lea  (without Mentions)
0.7455647572095764
Arbel vs. Elisheva  No Singletons Conll score by muc, bcub, ceafe, lea  (without Mentions)
0.7476482155152548
Elisheva vs. Ido No Singletons Conll score by muc, bcub, ceafe, lea  (without Mentions)
0.7685063102445977

In [9]:
should_keep_singleton = False
include_mentions = False
scores = n_annotators_agreement(["Arbel", "Ido", "Elisheva"], should_keep_singleton,include_mentions, file_by_annotator, conllu_annotated_files_path)

keep_singletons: False
include_mentions: False
Check agreement for 3 files
name1:  Arbel
name2:  Ido
Number of file coules: 5
name1:  Arbel
name2:  Elisheva
Number of file coules: 5
name1:  Ido
name2:  Elisheva
Number of file coules: 5
30 and 31 singletons are removed from the key and system files, respectively
mentions   Recall: 80.00  Precision: 85.71  F1: 82.76
muc        Recall: 62.50  Precision: 71.43  F1: 66.67
bcub       Recall: 72.22  Precision: 78.57  F1: 75.26
ceafe      Recall: 84.29  Precision: 84.29  F1: 84.29
lea        Recall: 66.67  Precision: 71.43  F1: 68.97
CoNLL score: 73.80
41 and 41 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 73.33  F1: 73.33
muc        Recall: 77.78  Precision: 70.00  F1: 73.68
bcub       Recall: 73.33  Precision: 68.33  F1: 70.75
ceafe      Recall: 64.29  Precision: 77.14  F1: 70.13
lea        Recall: 73.33  Precision: 66.67  F1: 69.84
CoNLL score: 71.10
47 and 59 singletons are removed from the key and system files, respectively
mentions   Recall: 68.89  Precision: 93.94  F1: 79.49
muc        Recall: 53.12  Precision: 80.95  F1: 64.15
bcub       Recall: 44.23  Precision: 83.03  F1: 57.71
ceafe      Recall: 54.54  Precision: 59.08  F1: 56.72
lea        Recall: 35.56  Precision: 75.76  F1: 48.40
CoNLL score: 56.75
29 and 24 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 83.87  F1: 91.23
muc        Recall: 100.00  Precision: 83.33  F1: 90.91
bcub       Recall: 100.00  Precision: 81.72  F1: 89.94
ceafe      Recall: 98.18  Precision: 83.08  F1: 90.00
lea        Recall: 100.00  Precision: 80.65  F1: 89.29
CoNLL score: 90.03
34 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 85.71  Precision: 88.24  F1: 86.96
muc        Recall: 79.17  Precision: 86.36  F1: 82.61
bcub       Recall: 77.62  Precision: 84.80  F1: 81.05
ceafe      Recall: 86.97  Precision: 79.72  F1: 83.19
lea        Recall: 73.33  Precision: 82.35  F1: 77.58
CoNLL score: 81.11
30 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 66.67  Precision: 100.00  F1: 80.00
muc        Recall: 62.50  Precision: 100.00  F1: 76.92
bcub       Recall: 62.22  Precision: 100.00  F1: 76.71
ceafe      Recall: 68.57  Precision: 96.00  F1: 80.00
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 77.16
41 and 45 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 100.00  F1: 84.62
muc        Recall: 66.67  Precision: 100.00  F1: 80.00
bcub       Recall: 64.44  Precision: 100.00  F1: 78.38
ceafe      Recall: 76.67  Precision: 92.00  F1: 83.64
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 79.25
47 and 70 singletons are removed from the key and system files, respectively
mentions   Recall: 44.44  Precision: 90.91  F1: 59.70
muc        Recall: 34.38  Precision: 84.62  F1: 48.89
bcub       Recall: 25.80  Precision: 86.36  F1: 39.73
ceafe      Recall: 37.69  Precision: 54.44  F1: 44.55
lea        Recall: 21.27  Precision: 81.82  F1: 33.76
CoNLL score: 41.73
29 and 26 singletons are removed from the key and system files, respectively
mentions   Recall: 92.31  Precision: 82.76  F1: 87.27
muc        Recall: 93.33  Precision: 82.35  F1: 87.50
bcub       Recall: 92.31  Precision: 80.46  F1: 85.98
ceafe      Recall: 89.09  Precision: 81.67  F1: 85.22
lea        Recall: 92.31  Precision: 79.31  F1: 85.32
CoNLL score: 86.00
34 and 37 singletons are removed from the key and system files, respectively
mentions   Recall: 88.57  Precision: 96.88  F1: 92.54
muc        Recall: 87.50  Precision: 95.45  F1: 91.30
bcub       Recall: 84.52  Precision: 94.79  F1: 89.36
ceafe      Recall: 85.97  Precision: 94.57  F1: 90.07
lea        Recall: 82.86  Precision: 93.75  F1: 87.97
CoNLL score: 89.68
41 and 45 singletons are removed from the key and system files, respectively
mentions   Recall: 60.00  Precision: 81.82  F1: 69.23
muc        Recall: 50.00  Precision: 83.33  F1: 62.50
bcub       Recall: 48.89  Precision: 81.82  F1: 61.21
ceafe      Recall: 69.33  Precision: 69.33  F1: 69.33
lea        Recall: 44.44  Precision: 81.82  F1: 57.60
CoNLL score: 62.66
24 and 26 singletons are removed from the key and system files, respectively
mentions   Recall: 93.55  Precision: 100.00  F1: 96.67
muc        Recall: 94.44  Precision: 100.00  F1: 97.14
bcub       Recall: 93.55  Precision: 100.00  F1: 96.67
ceafe      Recall: 92.31  Precision: 100.00  F1: 96.00
lea        Recall: 93.55  Precision: 100.00  F1: 96.67
CoNLL score: 96.62
31 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 64.29  Precision: 90.00  F1: 75.00
muc        Recall: 57.14  Precision: 80.00  F1: 66.67
bcub       Recall: 60.71  Precision: 85.00  F1: 70.83
ceafe      Recall: 64.29  Precision: 90.00  F1: 75.00
lea        Recall: 57.14  Precision: 80.00  F1: 66.67
CoNLL score: 69.79
59 and 70 singletons are removed from the key and system files, respectively
mentions   Recall: 66.67  Precision: 100.00  F1: 80.00
muc        Recall: 61.90  Precision: 100.00  F1: 76.47
bcub       Recall: 53.94  Precision: 100.00  F1: 70.08
ceafe      Recall: 61.90  Precision: 82.54  F1: 70.75
lea        Recall: 51.73  Precision: 100.00  F1: 68.19
CoNLL score: 71.37
35 and 37 singletons are removed from the key and system files, respectively
mentions   Recall: 85.29  Precision: 90.62  F1: 87.88
muc        Recall: 86.36  Precision: 86.36  F1: 86.36
bcub       Recall: 83.82  Precision: 84.90  F1: 84.36
ceafe      Recall: 75.83  Precision: 91.00  F1: 82.73
lea        Recall: 82.35  Precision: 81.25  F1: 81.80
CoNLL score: 83.81

In [10]:
print('Total score of "Arbel", "Ido", "Elisheva" with mentions: ')
data = {'values': [pd.DataFrame(score).loc['f1'].mean() for score in scores]}
df = pd.DataFrame(data)


print(df['values'].mean())

Total score of "Arbel", "Ido", "Elisheva" with mentions:
0.7539064276564762

In [11]:
should_keep_singleton = False
include_mentions = False
scores = n_annotators_agreement(["Arbel", "Ido", "Elisheva"], should_keep_singleton,include_mentions, file_by_annotator, conllu_annotated_files_path)

keep_singletons: False
include_mentions: False
Check agreement for 3 files
name1:  Arbel
name2:  Ido
Number of file coules: 5
name1:  Arbel
name2:  Elisheva
Number of file coules: 5
name1:  Ido
name2:  Elisheva
Number of file coules: 5
30 and 31 singletons are removed from the key and system files, respectively
mentions   Recall: 80.00  Precision: 85.71  F1: 82.76
muc        Recall: 62.50  Precision: 71.43  F1: 66.67
bcub       Recall: 72.22  Precision: 78.57  F1: 75.26
ceafe      Recall: 84.29  Precision: 84.29  F1: 84.29
lea        Recall: 66.67  Precision: 71.43  F1: 68.97
CoNLL score: 73.80
41 and 41 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 73.33  F1: 73.33
muc        Recall: 77.78  Precision: 70.00  F1: 73.68
bcub       Recall: 73.33  Precision: 68.33  F1: 70.75
ceafe      Recall: 64.29  Precision: 77.14  F1: 70.13
lea        Recall: 73.33  Precision: 66.67  F1: 69.84
CoNLL score: 71.10
47 and 59 singletons are removed from the key and system files, respectively
mentions   Recall: 68.89  Precision: 93.94  F1: 79.49
muc        Recall: 53.12  Precision: 80.95  F1: 64.15
bcub       Recall: 44.23  Precision: 83.03  F1: 57.71
ceafe      Recall: 54.54  Precision: 59.08  F1: 56.72
lea        Recall: 35.56  Precision: 75.76  F1: 48.40
CoNLL score: 56.75
29 and 24 singletons are removed from the key and system files, respectively
mentions   Recall: 100.00  Precision: 83.87  F1: 91.23
muc        Recall: 100.00  Precision: 83.33  F1: 90.91
bcub       Recall: 100.00  Precision: 81.72  F1: 89.94
ceafe      Recall: 98.18  Precision: 83.08  F1: 90.00
lea        Recall: 100.00  Precision: 80.65  F1: 89.29
CoNLL score: 90.03
34 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 85.71  Precision: 88.24  F1: 86.96
muc        Recall: 79.17  Precision: 86.36  F1: 82.61
bcub       Recall: 77.62  Precision: 84.80  F1: 81.05
ceafe      Recall: 86.97  Precision: 79.72  F1: 83.19
lea        Recall: 73.33  Precision: 82.35  F1: 77.58
CoNLL score: 81.11
30 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 66.67  Precision: 100.00  F1: 80.00
muc        Recall: 62.50  Precision: 100.00  F1: 76.92
bcub       Recall: 62.22  Precision: 100.00  F1: 76.71
ceafe      Recall: 68.57  Precision: 96.00  F1: 80.00
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 77.16
41 and 45 singletons are removed from the key and system files, respectively
mentions   Recall: 73.33  Precision: 100.00  F1: 84.62
muc        Recall: 66.67  Precision: 100.00  F1: 80.00
bcub       Recall: 64.44  Precision: 100.00  F1: 78.38
ceafe      Recall: 76.67  Precision: 92.00  F1: 83.64
lea        Recall: 60.00  Precision: 100.00  F1: 75.00
CoNLL score: 79.25
47 and 70 singletons are removed from the key and system files, respectively
mentions   Recall: 44.44  Precision: 90.91  F1: 59.70
muc        Recall: 34.38  Precision: 84.62  F1: 48.89
bcub       Recall: 25.80  Precision: 86.36  F1: 39.73
ceafe      Recall: 37.69  Precision: 54.44  F1: 44.55
lea        Recall: 21.27  Precision: 81.82  F1: 33.76
CoNLL score: 41.73
29 and 26 singletons are removed from the key and system files, respectively
mentions   Recall: 92.31  Precision: 82.76  F1: 87.27
muc        Recall: 93.33  Precision: 82.35  F1: 87.50
bcub       Recall: 92.31  Precision: 80.46  F1: 85.98
ceafe      Recall: 89.09  Precision: 81.67  F1: 85.22
lea        Recall: 92.31  Precision: 79.31  F1: 85.32
CoNLL score: 86.00
34 and 37 singletons are removed from the key and system files, respectively
mentions   Recall: 88.57  Precision: 96.88  F1: 92.54
muc        Recall: 87.50  Precision: 95.45  F1: 91.30
bcub       Recall: 84.52  Precision: 94.79  F1: 89.36
ceafe      Recall: 85.97  Precision: 94.57  F1: 90.07
lea        Recall: 82.86  Precision: 93.75  F1: 87.97
CoNLL score: 89.68
41 and 45 singletons are removed from the key and system files, respectively
mentions   Recall: 60.00  Precision: 81.82  F1: 69.23
muc        Recall: 50.00  Precision: 83.33  F1: 62.50
bcub       Recall: 48.89  Precision: 81.82  F1: 61.21
ceafe      Recall: 69.33  Precision: 69.33  F1: 69.33
lea        Recall: 44.44  Precision: 81.82  F1: 57.60
CoNLL score: 62.66
24 and 26 singletons are removed from the key and system files, respectively
mentions   Recall: 93.55  Precision: 100.00  F1: 96.67
muc        Recall: 94.44  Precision: 100.00  F1: 97.14
bcub       Recall: 93.55  Precision: 100.00  F1: 96.67
ceafe      Recall: 92.31  Precision: 100.00  F1: 96.00
lea        Recall: 93.55  Precision: 100.00  F1: 96.67
CoNLL score: 96.62
31 and 35 singletons are removed from the key and system files, respectively
mentions   Recall: 64.29  Precision: 90.00  F1: 75.00
muc        Recall: 57.14  Precision: 80.00  F1: 66.67
bcub       Recall: 60.71  Precision: 85.00  F1: 70.83
ceafe      Recall: 64.29  Precision: 90.00  F1: 75.00
lea        Recall: 57.14  Precision: 80.00  F1: 66.67
CoNLL score: 69.79
59 and 70 singletons are removed from the key and system files, respectively
mentions   Recall: 66.67  Precision: 100.00  F1: 80.00
muc        Recall: 61.90  Precision: 100.00  F1: 76.47
bcub       Recall: 53.94  Precision: 100.00  F1: 70.08
ceafe      Recall: 61.90  Precision: 82.54  F1: 70.75
lea        Recall: 51.73  Precision: 100.00  F1: 68.19
CoNLL score: 71.37
35 and 37 singletons are removed from the key and system files, respectively
mentions   Recall: 85.29  Precision: 90.62  F1: 87.88
muc        Recall: 86.36  Precision: 86.36  F1: 86.36
bcub       Recall: 83.82  Precision: 84.90  F1: 84.36
ceafe      Recall: 75.83  Precision: 91.00  F1: 82.73
lea        Recall: 82.35  Precision: 81.25  F1: 81.80
CoNLL score: 83.81

In [12]:
print('Total score of "Arbel", "Ido", "Elisheva" no mentions: ')
data_no_mentions = {'values': [pd.DataFrame(score).loc['f1'].mean() for score in scores]}
df_no_mentions = pd.DataFrame(data_no_mentions)
print(df_no_mentions['values'].mean())

Total score of "Arbel", "Ido", "Elisheva" no mentions:
0.7539064276564762

In [13]:
scores

[{'muc': {'recall': 0.7451388888888888,
   'precision': 0.7841558441558443,
   'f1': 0.7560392143009474},
  'bcub': {'recall': 0.7348059964726631,
   'precision': 0.7929188332224386,
   'f1': 0.7494310842977099},
  'ceafe': {'recall': 0.7765211862044442,
   'precision': 0.7666203404438698,
   'f1': 0.7686462911342706},
  'lea': {'recall': 0.6977777777777778,
   'precision': 0.753701832639214,
   'f1': 0.708142439105378}},
 {'muc': {'recall': 0.68875,
   'precision': 0.9248457424928013,
   'f1': 0.7692326272761056},
  'bcub': {'recall': 0.658601275267942,
   'precision': 0.9232301462904913,
   'f1': 0.7403315832801202},
  'ceafe': {'recall': 0.715990675990676,
   'precision': 0.8373650793650793,
   'f1': 0.7669344733941006},
  'lea': {'recall': 0.6328693528693529,
   'precision': 0.9097570532915361,
   'f1': 0.7140941781106929}},
 {'muc': {'recall': 0.6997113997113997,
   'precision': 0.8993939393939394,
   'f1': 0.7782874968169086},
  'bcub': {'recall': 0.6818289701022149,
   'precision': 0.9034280303030304,
   'f1': 0.7662811562659562},
  'ceafe': {'recall': 0.7273296703296703,
   'precision': 0.8657460317460318,
   'f1': 0.7876178107606678},
  'lea': {'recall': 0.6584404631842962,
   'precision': 0.8861363636363636,
   'f1': 0.7418387771348582}}]

In [14]:
print(pd.DataFrame(scores[2]))

                muc      bcub     ceafe       lea
recall     0.699711  0.681829  0.727330  0.658440
precision  0.899394  0.903428  0.865746  0.886136
f1         0.778287  0.766281  0.787618  0.741839

In [20]:
df_no_mentions

     values
0  0.745565
1  0.747648
2  0.768506

     values
0  0.745565
1  0.747648
2  0.768506